title: Stux | Blog
description: Writeups hack the box & Tryhackme, Mobile Hacking
google_analytics:
google_site_verification_content: 
#disqus_forum_shortname: captainirs-github-io

#Usernames and badges
htb_badge_no:
thm_badge_no:
show_thm_htb_badges_in_nav: false
github_username: stuxctf
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin: stuxnet
twitch:
youtube:
twitter: __stux
facebook:
instagram:
reddit:
pinterest:
telegram: stuxnet
steam:

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   blog:
      output: true
